# Generated by Django 5.0 on 2025-05-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Board', max_length=255)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('saw_thickness', models.FloatField(default=3.2)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='optimized_cuts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
