# Generated by Django 5.0 on 2025-01-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_alter_customer_email_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='board', max_length=20, null=True)),
                ('dimX', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimY', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimZ', models.IntegerField(help_text='Dimension in milimeters')),
                ('quantity', models.IntegerField(null=True)),
                ('wood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wood')),
            ],
        ),
    ]
