# Generated by Django 5.0 on 2025-02-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstage',
            name='production',
        ),
        migrations.CreateModel(
            name='ProductionStageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='production.production')),
                ('production_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_stage', to='production.productionstage')),
            ],
        ),
    ]
