# Generated by Django 5.0 on 2025-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_productionstage_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='production_stages',
        ),
        migrations.AddField(
            model_name='production',
            name='production_stages',
            field=models.ManyToManyField(blank=True, null=True, through='production.ProductionStageDetails', to='production.productionstage'),
        ),
    ]
