# Generated by Django 5.0 on 2025-02-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_rename_productionstagedetails_orderproductionstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstage',
            name='is_done',
        ),
        migrations.AddField(
            model_name='orderproductionstage',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_stages',
            field=models.ManyToManyField(blank=True, through='production.OrderProductionStage', to='production.productionstage'),
        ),
    ]
