# Generated by Django 5.0 on 2025-02-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionstage_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductionstage',
            name='production_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionstage'),
        ),
    ]
