# Generated by Django 5.0 on 2025-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_orderproductionstage_production_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
