# Generated by Django 5.0 on 2025-04-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_customer_email_alter_customer_phone_number'),
        ('production', '0008_production_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
    ]
