# Generated by Django 5.0 on 2025-04-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_production_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='production_stages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionstage'),
        ),
    ]
