# Generated by Django 5.0 on 2025-04-15 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_catalogproduct_production_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
