# Generated by Django 5.0 on 2025-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_production_created_at_production_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
