# Generated by Django 5.0 on 2025-05-10 20:00

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('Prowadnice', 'Prowadnice'), ('Złącza', 'Złącza'), ('Zawiasy', 'Zawiasy')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_accesory_type',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('partners', models.CharField(blank=True, choices=[('Visby', 'Visby'), ('Seart', 'Seart'), ('Desiq', 'Desiq')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=15, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.ImageField(upload_to=product.models.documents_user_directory_path)),
                ('date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=3, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dimX', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimY', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimZ', models.IntegerField(help_text='Dimension in milimeters')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=product.models.documents_user_directory_path)),
                ('date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=3, null=3)),
                ('size', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField(blank=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='litr', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0)),
                ('workers', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('density', models.FloatField(help_text='Density in kg/m3')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in zl/m3', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worktimetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField(help_text='Cost of one hour worktime')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.accessorytype')),
            ],
        ),
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worktime_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elements_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elements_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accesories_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accesories_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_with_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_without_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_elements_margin', models.IntegerField(blank=True, null=True)),
                ('percent_accesories_margin', models.IntegerField(blank=True, null=True)),
                ('percent_additional_margin', models.IntegerField(blank=True, null=True)),
                ('accessories', models.ManyToManyField(blank=True, through='product.AccessoryDetail', to='product.accessorytype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('document', models.ManyToManyField(blank=True, to='product.document')),
                ('image', models.ManyToManyField(blank=True, to='product.image')),
            ],
        ),
    ]
