# Generated by Django 5.0 on 2024-07-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('Prowadnice', 'Prowadnice'), ('Złącza', 'Złącza'), ('Zawiasy', 'Zawiasy')], max_length=50)),
            ],
            options={
                'db_table': 'product_accesory_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('partners', models.CharField(blank=True, choices=[('Visby', 'Visby'), ('Seart', 'Seart'), ('Desiq', 'Desiq')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dimX', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimY', models.IntegerField(help_text='Dimension in milimeters')),
                ('dimZ', models.IntegerField(help_text='Dimension in milimeters')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField(blank=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='litr', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('density', models.FloatField(help_text='Density in kg/m3')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in zl/m3', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worktimetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField(help_text='Cost of one hour worktime')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.accessorytype')),
            ],
        ),
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elements_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accesories_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_with_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_without_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accessories', models.ManyToManyField(blank=True, through='product.AccessoryDetail', to='product.accessorytype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
            ],
        ),
        migrations.AddField(
            model_name='accessorydetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.newproject'),
        ),
        migrations.CreateModel(
            name='NewProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.element')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_elements', to='product.newproject')),
            ],
        ),
        migrations.AddField(
            model_name='newproject',
            name='new_elements',
            field=models.ManyToManyField(blank=True, through='product.NewProjectElement', to='product.element'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='paints',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.paints'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
                ('elements', models.ManyToManyField(to='product.element')),
                ('paints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.paints')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='newproject',
            name='wood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wood'),
        ),
        migrations.AddField(
            model_name='element',
            name='wood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wood'),
        ),
        migrations.CreateModel(
            name='ProjectWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0)),
                ('workers', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.newproject')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.worktimetype')),
            ],
        ),
        migrations.AddField(
            model_name='newproject',
            name='worktimes',
            field=models.ManyToManyField(blank=True, through='product.ProjectWorktime', to='product.worktimetype'),
        ),
    ]
