# Generated by Django 5.0 on 2025-06-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='accesories_cost',
            new_name='accessories_cost',
        ),
        migrations.RenameField(
            model_name='newproject',
            old_name='accesories_margin',
            new_name='accessories_margin',
        ),
        migrations.RenameField(
            model_name='newproject',
            old_name='percent_accesories_margin',
            new_name='percent_accessories_margin',
        ),
        migrations.AlterField(
            model_name='accessorydetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accessories', to='product.newproject'),
        ),
    ]
