# Generated by Django 5.0 on 2024-08-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_newproject_percent_accesories_margin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='percent_additionak_margin',
            new_name='percent_additional_margin',
        ),
    ]
