# Generated by Django 5.0 on 2024-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_projectworktime_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='worktime_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
