# Generated by Django 5.0 on 2024-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_type_document_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
