# Generated by Django 5.0 on 2024-08-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='percent_accesories_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newproject',
            name='percent_additionak_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newproject',
            name='percent_elements_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessorydetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesories', to='product.newproject'),
        ),
    ]
