# Generated by Django 5.0.4 on 2024-06-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='worktimes',
        ),
        migrations.AlterModelTable(
            name='accessorytype',
            table='product_accesory_type',
        ),
    ]
