# Generated by Django 5.0.4 on 2024-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_worktimetype_workers_worktime_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorytype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
