# Generated by Django 5.0.4 on 2024-06-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_accessories_remove_product_worktimes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.newproject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.accessorytype')),
            ],
        ),
        migrations.AlterField(
            model_name='newproject',
            name='accessories',
            field=models.ManyToManyField(blank=True, through='product.AccessoryDetail', to='product.accessorytype'),
        ),
        migrations.DeleteModel(
            name='ProjectAccesories',
        ),
    ]
