# Generated by Django 5.0.4 on 2024-06-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_accessorydetail_alter_newproject_accessories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
