# Generated by Django 5.0.4 on 2024-06-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworktime',
            name='worktime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.worktimetype'),
        ),
        migrations.RemoveField(
            model_name='balance',
            name='worktime',
        ),
        migrations.AddField(
            model_name='projectworktime',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projectworktime',
            name='workers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='worktimes',
            field=models.ManyToManyField(blank=True, through='product.ProjectWorktime', to='product.worktimetype'),
        ),
        migrations.DeleteModel(
            name='Worktime',
        ),
    ]
