# Generated by Django 5.0 on 2024-06-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_projectworktime_worktime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='elements',
        ),
        migrations.CreateModel(
            name='NewProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.element')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.newproject')),
            ],
        ),
        migrations.AddField(
            model_name='newproject',
            name='new_elements',
            field=models.ManyToManyField(blank=True, through='product.NewProjectElement', to='product.element'),
        ),
    ]
