# Generated by Django 5.0.4 on 2024-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_element_wood_type_delete_woodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in zl/m3', max_digits=15),
        ),
        migrations.DeleteModel(
            name='ProductElement',
        ),
    ]
