# Generated by Django 5.0.4 on 2024-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_element_price_alter_wood_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorytype',
            name='type',
            field=models.CharField(choices=[('Prowadnice', 'Prowadnice'), ('Złącza', 'Złącza'), ('Zawiasy', 'Zawiasy')], default='Prowadnice', max_length=50),
        ),
    ]
