# Generated by Django 5.0 on 2024-10-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_customer_document_image_newproject_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='product.newproject'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.newproject'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='document',
            field=models.ManyToManyField(blank=True, to='product.document'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='image',
            field=models.ManyToManyField(blank=True, to='product.image'),
        ),
    ]
