# Generated by Django 5.0.4 on 2024-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_accessorytype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorytype',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
