# Generated by Django 5.0.4 on 2024-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_accessorytype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorytype',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accessorytype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
