# Generated by Django 5.0 on 2024-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_document_project_image_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(max_length=3, null=3),
            preserve_default=3,
        ),
    ]
