# Generated by Django 5.0 on 2024-10-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_document_type_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
