# Generated by Django 5.0.4 on 2024-05-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_accessorytype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elements_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accesories_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary_with_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary_without_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessories', models.ManyToManyField(blank=True, to='product.accessory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
                ('elements', models.ManyToManyField(to='product.element')),
                ('paints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.paints')),
                ('worktimes', models.ManyToManyField(blank=True, to='product.worktime')),
            ],
        ),
    ]
