# Generated by Django 5.0 on 2024-10-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_document_size_image_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='file_type',
        ),
    ]
