# Generated by Django 5.0.4 on 2024-05-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_newproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='wood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wood'),
        ),
    ]
