# Generated by Django 5.0.4 on 2024-06-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_newproject_wood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='type',
            new_name='name',
        ),
        migrations.CreateModel(
            name='ProjectWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.newproject')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.worktime')),
            ],
        ),
        migrations.AlterField(
            model_name='newproject',
            name='worktimes',
            field=models.ManyToManyField(blank=True, through='product.ProjectWorktime', to='product.worktime'),
        ),
    ]
