# Generated by Django 5.0.4 on 2024-06-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_newproject_wood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='type',
            new_name='name',
        ),
    ]
