# Generated by Django 5.0 on 2025-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_customer_email_alter_customer_phone_number'),
        ('production', '0012_alter_catalogproduct_production_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='production_stages',
            field=models.ManyToManyField(blank=True, to='production.productionstage'),
        ),
    ]
