# Generated by Django 5.0 on 2025-05-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('shortcut', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogAccessoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.accessorytype')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.element')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worktime_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elements_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elements_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accesories_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accesories_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_with_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('summary_without_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_elements_margin', models.IntegerField(blank=True, null=True)),
                ('percent_accesories_margin', models.IntegerField(blank=True, null=True)),
                ('percent_additional_margin', models.IntegerField(blank=True, null=True)),
                ('accessories', models.ManyToManyField(blank=True, through='production.CatalogAccessoryDetail', to='product.accessorytype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.collection')),
                ('document', models.ManyToManyField(blank=True, to='product.document')),
                ('image', models.ManyToManyField(blank=True, to='product.image')),
                ('new_elements', models.ManyToManyField(blank=True, through='production.CatalogElement', to='product.element')),
                ('paints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.paints')),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wood')),
            ],
        ),
        migrations.AddField(
            model_name='catalogelement',
            name='catalog_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_elements', to='production.catalogproduct'),
        ),
        migrations.AddField(
            model_name='catalogaccessorydetail',
            name='catalog_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_accessories', to='production.catalogproduct'),
        ),
        migrations.CreateModel(
            name='CatalogWorktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0)),
                ('workers', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_worktime', to='production.catalogproduct')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.worktimetype')),
            ],
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='worktimes',
            field=models.ManyToManyField(blank=True, through='production.CatalogWorktime', to='product.worktimetype'),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('date_ordered', models.DateField()),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='production.production')),
                ('production_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionstage')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='production_stages',
            field=models.ManyToManyField(blank=True, through='production.OrderProductionStage', to='production.productionstage'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='production_stages',
            field=models.ManyToManyField(blank=True, to='production.productionstage'),
        ),
    ]
