# Generated by Django 5.0 on 2025-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstage',
            name='shortcut',
            field=models.CharField(max_length=3),
        ),
    ]
