# Generated by Django 5.0 on 2025-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionstage_shortcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogproduct',
            old_name='accesories_cost',
            new_name='accessories_cost',
        ),
        migrations.RenameField(
            model_name='catalogproduct',
            old_name='accesories_margin',
            new_name='accessories_margin',
        ),
        migrations.RenameField(
            model_name='catalogproduct',
            old_name='percent_accesories_margin',
            new_name='percent_accessories_margin',
        ),
    ]
