# Generated by Django 5.0 on 2025-02-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_production_production_stages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionStageDetails',
            new_name='OrderProductionStage',
        ),
    ]
