# Generated by Django 5.0 on 2025-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_productionstage_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='shortcut',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
