# Generated by Django 5.0 on 2025-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_catalogproduct_production_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='production_stages',
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='production_stages',
            field=models.ManyToManyField(blank=True, null=True, to='production.productionstage'),
        ),
    ]
