# Generated by Django 5.0 on 2025-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_remove_catalogproduct_production_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='production_stages',
            field=models.ManyToManyField(blank=True, to='production.productionstage'),
        ),
    ]
